- repo: https://github.com/asottile/seed-isort-config
  rev: v1.5.0
  hooks:
    - id: seed-isort-config
      args: [--application-directories=tanmt]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: "v4.3.4"
  hooks:
    - id: isort
      args: [--check-only, --diff, --quiet]
- repo: https://gitlab.com/pycqa/flake8
  rev: "3.7.5"
  hooks:
    - id: flake8
      args: [--config=setup.cfg]
      exclude: migrations|env
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: 'v0.28.0'
  hooks:
    - id: yapf
      args: [--diff, --exclude=*migrations*]
