repos:
- repo: https://github.com/PyCQA/isort
  rev: "5.13.2"
  hooks:
    - id: isort
      args: [--check-only, --diff, --quiet]
      exclude: migrations|env
- repo: https://github.com/PyCQA/flake8
  rev: "7.0.0"
  hooks:
    - id: flake8
      args: [--config=setup.cfg]
      exclude: migrations|env
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: 'v0.32.0'
  hooks:
    - id: yapf
      args: [--diff]
      exclude: migrations|env
