# Generated by Django 2.2.6 on 2019-12-09 11:27

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='This will be the URL for this page', overwrite=True, populate_from='title', unique=True),
        ),
    ]
