# Generated by Django 2.2.6 on 2019-10-29 16:10

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import pictures.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='This is used as the URL for this tag', max_length=200, populate_from='tag')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1000, help_text='The lower the number, the sooner this picture will be published')),
                ('title', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='This is used as the URL for this picture', max_length=200, populate_from='title')),
                ('description', models.TextField(blank=True, null=True)),
                ('published_id', models.PositiveIntegerField(blank=True, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='pictures.Tag')),
            ],
            options={
                'ordering': ['order', 'created_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pictures.models.Image.get_upload_path)),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pictures.Picture')),
            ],
        ),
    ]
