# Generated by Django 2.2.6 on 2019-12-16 14:01

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_auto_20191209_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='This is used as the URL for this tag', max_length=200, overwrite=True, populate_from='tag', unique=True),
        ),
    ]
