# Generated by Django 2.2.6 on 2019-12-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20191216_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField(blank=True, help_text='Tags to be added to every picture published on social media (#AddHashes #ManuallyCapitaliseWords #AddSpacesBetweenTags)', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='extra_tags',
            field=models.TextField(blank=True, help_text='Tags to be added to this picture when published on social media (#AddHashes #ManuallyCapitaliseWords #AddSpacesBetweenTags)', null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='extra_tags',
            field=models.TextField(blank=True, help_text='Tags to be added to every picture in this category published on social media (#AddHashes #ManuallyCapitaliseWords #AddSpacesBetweenTags)', null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Main categories used on website', to='pictures.Tag'),
        ),
    ]
