# Generated by Django 2.2.6 on 2019-12-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20191219_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globaltags',
            options={'verbose_name': 'Global tags', 'verbose_name_plural': 'Global tags'},
        ),
        migrations.AlterField(
            model_name='globaltags',
            name='tags',
            field=models.TextField(blank=True, help_text='Tags to be added to every picture published on social media<br>(#AddHashes #ManuallyCapitaliseWords #AddSpacesBetweenTags)', null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='extra_tags',
            field=models.TextField(blank=True, help_text='Tags to be added to this picture when published on social media<br>(#AddHashes #ManuallyCapitaliseWords #AddSpacesBetweenTags)', null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='extra_tags',
            field=models.TextField(blank=True, help_text='Tags to be added to every picture in this category published on social media<br>(#AddHashes #ManuallyCapitaliseWords #AddSpacesBetweenTags)', null=True),
        ),
    ]
